"""FastAPI application factory + ``wordcount-api`` entrypoint.

``create_app()`` assembles the connector: CORS (any UX origin), ProblemDetails
exception handlers (§6.3), and the routers that thinly wrap ``core/``. The
OpenAPI spec at ``/docs`` is the contract for any future UX (codegen from
``/openapi.json``); a committed snapshot is regenerated by
``wordcount-api --generate-openapi``.

``run()`` is the ``[project.scripts]`` entrypoint: ``uvicorn.run`` with the app
factory. ``--generate-openapi`` writes the spec to ``api/openapi.json`` and
exits (used by CI to keep the committed snapshot in sync).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from wordcount.api.deps import get_settings
from wordcount.api.errors import register_exception_handlers
from wordcount.api.routers import (
    analysis,
    datasets,
    detected,
    enhanced,
    export,
    health,
    stats,
    wordlists,
)
from wordcount.api.settings import Settings


def create_app(settings: Settings | None = None) -> FastAPI:
    """Build a FastAPI app with CORS, error handlers, and all routers mounted."""
    settings = settings or get_settings()
    app = FastAPI(
        title=settings.api_title,
        version=settings.api_version,
        description=(
            "Dataset + vocabulary → enhanced dataset + analytics. "
            "Stateless connector over the pure `wordcount.core` library."
        ),
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    register_exception_handlers(app)

    for r in (
        health.router,
        datasets.router,
        wordlists.router,
        analysis.router,
        enhanced.router,
        detected.router,
        stats.router,
        export.router,
    ):
        app.include_router(r)

    return app


def _write_openapi_snapshot(path: Path) -> None:
    """Write the current OpenAPI spec to ``path`` (CI snapshot)."""
    spec = create_app().openapi()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(spec, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def run(argv: list[str] | None = None) -> None:
    """``wordcount-api`` entrypoint: serve, or regenerate the OpenAPI snapshot."""
    args = sys.argv[1:] if argv is None else argv
    if "--generate-openapi" in args:
        out = Path("api/openapi.json")
        _write_openapi_snapshot(out)
        print(f"OpenAPI spec written to {out}")  # noqa: T201
        return

    import uvicorn  # noqa: PLC0415

    uvicorn.run(
        "wordcount.api.app:create_app",
        factory=True,
        host="0.0.0.0",
        port=8000,
        reload="--reload" in args,
    )


__all__ = ["create_app", "run"]
